services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
